### ISSUE TITLE
[Bug]: Fix ML circular import and enforce CLI dependency boundaries

### ISSUE THREAD

**Issue by rparanjape** [Team-Gurubodh/gurubodh#278]
## Problem

The reusable `gurubodh.ml.embeddings` module fails when imported first in a fresh Python process. The complete unit suite passes because earlier imports initialize the semantic-chunking package in a working order, masking the defect.

Dependency analysis associated with #274 established the failing sequence:

```text
ml.embeddings
  -> requests semantic_chunking.config.ModelCacheConfigError
  -> Python initializes semantic_chunking/__init__.py
  -> __init__.py eagerly imports chunker
  -> chunker imports classes from the partially initialized ml.embeddings
  -> ImportError
```

`segmenter` participates in the larger static graph cycle through package re-exports but is not required to reproduce this failure. The embedding helper introduced in #210 currently depends on the more specialized chunking configuration module for a shared exception.

The SVG uses pydeps' default imported-module-to-importer arrow direction. Its edges do not mean that lower-level modules import the main CLI. The apparent `contracts`/proofreading cycle combines type-only imports, parent-package relationships, and a lazy compatibility export; importing `contracts` alone loads no other Gurubodh submodules. Do not treat those static edges as an equivalent runtime defect.

## Expected Behavior

Every Gurubodh package module can be imported independently in a fresh process. Configuration/model imports remain lightweight, embedding infrastructure is independent of semantic-chunking implementation, and automated checks preserve the existing direction from CLI/orchestration toward reusable components.

## Steps To Reproduce

From `tools/gurubodh-cli`, using the existing development environment:

```bash
PYTHONDONTWRITEBYTECODE=1 .venv/bin/python -B -c 'import gurubodh.ml.embeddings'
PYTHONDONTWRITEBYTECODE=1 .venv/bin/python -B -m unittest discover -s tests -p test_semantic_chunking.py -v
```

Both fail with:

```text
ImportError: cannot import name 'SentenceTransformerEmbeddingHelper'
from partially initialized module 'gurubodh.ml.embeddings'
```

## Environment and Baseline Verification

Read-only investigation on 2026-09-05 at revision `00dd65c`, macOS, Python 3.12.14:

- Full local unittest discovery: 195 tests passed.
- Separate-process imports of all 71 package modules: 70 passed; only `ml.embeddings` failed.
- Standalone semantic-chunking suite: failed during test-module import, before its tests executed.
- Separate imports of `contracts`, proofreading service, and Gemini adapter passed.
- Docker, live Gemini/R2 operations, and real-model comparisons were not run during the investigation.

## Scope

1. Move `ModelCacheConfigError` to a small ML-level leaf module, such as `gurubodh/ml/errors.py`, consumed by both embedding infrastructure and chunking configuration. Preserve a single exception class and the existing configuration import path where compatibility requires it.
2. Make `semantic_chunking/__init__.py` lightweight. Configuration/model imports must not eagerly load chunker, segmenter, or embedding implementation. Preserve supported package-level imports deliberately, using lazy compatibility exports where appropriate.
3. Add fresh-process import regression checks. Do not rely on a single process importing every module sequentially, because its module cache can mask this defect. Checks must not initialize providers, download models, or execute CLI workflows.
4. Add focused architectural checks for the agreed boundaries, building on the existing canonical-source/release import guard:
   - only the production entry point imports the main CLI;
   - reusable components do not import lab or command orchestrators;
   - canonical source/release validation remains independent of prep orchestration;
   - embedding infrastructure does not depend on semantic-chunking modules;
   - contract imports do not load services or provider adapters.
5. Distinguish explicit runtime imports, type-only references, compatibility exports, and implicit parent-package initialization when assessing dependencies. A direct-import scan alone is insufficient, and raw pydeps cycle counts are not an acceptance criterion.
6. Update the relevant internal-boundary documentation and ensure the checks run in the maintained verification path.

## Acceptance Criteria

- [ ] Both reproduction commands succeed in fresh processes.
- [ ] Every current package module passes an isolated import check without provider/model initialization or workflow execution.
- [ ] Importing semantic-chunking configuration or models does not load chunker, segmenter, or embedding implementation.
- [ ] Existing supported imports and `ModelCacheConfigError` catch behavior/class identity remain compatible.
- [ ] Boundary checks enforce the relationships above and run with normal CI verification.
- [ ] Deterministic fake-model tests preserve chunk text, spans, checksums, token counts, and contextual-only encoding behavior.
- [ ] Full CLI unittest discovery and `git diff --check` pass; the documented container smoke checks pass or any unavailable checks are reported explicitly.
- [ ] Relevant internal-workflow documentation describes the resulting ownership and import rules.

## Constraints and Risk

This is an import/ownership repair plus regression prevention. Keep chunking algorithms, model selection/revision, configuration fingerprints, artifact schemas and serialized output, command behavior, and publication sequencing unchanged. No contracts split, checkpoint redesign, broad package reorganization, or shared-audit diagnostics extraction is included; diagnostics ownership will be handled separately.

Expected change risk is low when confined to imports and ownership. Review compatibility exports, exception identity, independent component loading, and output equivalence explicitly.

Related: #274 (dependency graph), #210 (embedding-helper extraction), #269 (existing canonical/prep boundary).
